// SPDX-FileCopyrightText: 2025 Legiayayana <ada@chronovore.dev>
// SPDX-License-Identifier: EUPL-1.2

extension Journal.Event {
	/// Journal Event Registration and dispatch system.
	public struct Registry: Sendable {
		private let typeRegistry: [Journal.Event: Journal.Type]

		public static let `default`: Registry = Registry()

		init() {
			var typeRegistry: [Journal.Event: Journal.Type] = [:]

			typeRegistry[.allBodiesFound] = Journal.AllBodiesFound.self
			typeRegistry[.appliedToSquadron] = Journal.Squadron.self
			typeRegistry[.approachBody] = Journal.ApproachBody.self
			typeRegistry[.approachSettlement] = Journal.ApproachSettlement.self
			typeRegistry[.asteroidCracked] = Journal.AsteroidCracked.self
			typeRegistry[.autoDiscoveryScan] = Journal.AutoDiscoveryScan.self
			typeRegistry[.backpack] = Journal.Backpack.self
			typeRegistry[.backpackChange] = Journal.BackpackChange.self
			typeRegistry[.backpackMaterials] = Journal.BackpackMaterials.self
			typeRegistry[.bodySignals] = Journal.BodySignals.self
			typeRegistry[.bookDropship] = Journal.BookDropship.self
			typeRegistry[.bookTaxi] = Journal.BookTaxi.self
			typeRegistry[.bounty] = Journal.Bounty.self
			typeRegistry[.buggyDestroyed] = Journal.BuggyDestroyed.self
			typeRegistry[.buyAmmo] = Journal.BuyAmmo.self
			typeRegistry[.buyDrones] = Journal.BuyDrones.self
			typeRegistry[.buyExplorationData] = Journal.BuyExplorationData.self
			typeRegistry[.buyMicroResources] = Journal.BuyMicroResources.self
			typeRegistry[.buySuit] = Journal.BuySuit.self
			typeRegistry[.buyTradeData] = Journal.BuyTradeData.self
			typeRegistry[.buyWeapon] = Journal.BuyWeapon.self
			typeRegistry[.cancelDropship] = Journal.CancelDropship.self
			typeRegistry[.cancelTaxi] = Journal.CancelTaxi.self
			typeRegistry[.capitalShipBond] = Journal.CapitalShipBond.self
			typeRegistry[.cargo] = Journal.Cargo.self
			typeRegistry[.cargoDepot] = Journal.CargoDepot.self
			typeRegistry[.cargoTransfer] = Journal.CargoTransfer.self
			typeRegistry[.carrierBankTransfer] = Journal.CarrierBankTransfer.self
			typeRegistry[.carrierBuy] = Journal.CarrierBuy.self
			typeRegistry[.carrierCancelDecommission] = Journal.CarrierCancelDecommission.self
			typeRegistry[.carrierCrewServices] = Journal.CarrierCrewServices.self
			typeRegistry[.carrierDecommission] = Journal.CarrierDecommission.self
			typeRegistry[.carrierDepositFuel] = Journal.CarrierDepositFuel.self
			typeRegistry[.carrierDockingPermission] = Journal.CarrierDockingPermission.self
			typeRegistry[.carrierFinance] = Journal.CarrierFinance.self
			typeRegistry[.carrierJump] = Journal.CarrierJump.self
			typeRegistry[.carrierJumpCancelled] = Journal.CarrierJumpCancelled.self
			typeRegistry[.carrierJumpRequest] = Journal.CarrierJumpRequest.self
			typeRegistry[.carrierModulePack] = Journal.CarrierModulePack.self
			typeRegistry[.carrierNameChange] = Journal.CarrierNameChange.self
			typeRegistry[.carrierShipPack] = Journal.CarrierShipPack.self
			typeRegistry[.carrierStats] = Journal.CarrierStats.self
			typeRegistry[.carrierTradeOrder] = Journal.CarrierTradeOrder.self
			typeRegistry[.changeCrewRole] = Journal.ChangeCrewRole.self
			typeRegistry[.clearImpound] = Journal.ClearImpound.self
			typeRegistry[.clearSavedGame] = Journal.Commander.self
			typeRegistry[.cockpitBreached] = Journal.CockpitBreached.self
			typeRegistry[.codexEntry] = Journal.CodexEntry.self
			typeRegistry[.collectCargo] = Journal.CollectCargo.self
			typeRegistry[.collectItems] = Journal.CollectItems.self
			typeRegistry[.commander] = Journal.Commander.self
			typeRegistry[.commitCrime] = Journal.CommitCrime.self
			typeRegistry[.communityGoal] = Journal.CommunityGoal.self
			typeRegistry[.communityGoalDiscard] = Journal.CommunityGoalDiscard.self
			typeRegistry[.communityGoalJoin] = Journal.CommunityGoalJoin.self
			typeRegistry[.communityGoalReward] = Journal.CommunityGoalReward.self
			typeRegistry[.continued] = Journal.Continued.self
			typeRegistry[.createSuitLoadout] = Journal.CreateSuitLoadout.self
			typeRegistry[.crewAssign] = Journal.CrewAssign.self
			typeRegistry[.crewFire] = Journal.CrewFire.self
			typeRegistry[.crewHire] = Journal.CrewHire.self
			typeRegistry[.crewLaunchFighter] = Journal.CrewLaunchFighter.self
			typeRegistry[.crewMemberJoins] = Journal.CrewMemberJoins.self
			typeRegistry[.crewMemberQuits] = Journal.CrewMemberQuits.self
			typeRegistry[.crewMemberRoleChange] = Journal.CrewMemberRoleChange.self
			typeRegistry[.crimeVictim] = Journal.CrimeVictim.self
			typeRegistry[.datalinkScan] = Journal.DatalinkScan.self
			typeRegistry[.datalinkVoucher] = Journal.DatalinkVoucher.self
			typeRegistry[.dataScanned] = Journal.DataScanned.self
			typeRegistry[.deleteSuitLoadout] = Journal.DeleteSuitLoadout.self
			typeRegistry[.deliverPowerMicroResources] = Journal.DeliverPowerMicroResources.self
			typeRegistry[.died] = Journal.Died.self
			typeRegistry[.disbandedSquadron] = Journal.Squadron.self
			typeRegistry[.discoveryScan] = Journal.DiscoveryScan.self
			typeRegistry[.disembark] = Journal.Disembark.self
			typeRegistry[.dockBuggy] = Journal.DockBuggy.self
			typeRegistry[.docked] = Journal.Docked.self
			typeRegistry[.dockFighter] = Journal.DockFighter.self
			typeRegistry[.dockingCancelled] = Journal.DockingCancelled.self
			typeRegistry[.dockingDenied] = Journal.DockingDenied.self
			typeRegistry[.dockingGranted] = Journal.DockingGranted.self
			typeRegistry[.dockingRequested] = Journal.DockingRequested.self
			typeRegistry[.dockingTimeout] = Journal.DockingTimeout.self
			typeRegistry[.dropItems] = Journal.DropItems.self
			typeRegistry[.dropshipDeploy] = Journal.DropshipDeploy.self
			typeRegistry[.ejectCargo] = Journal.EjectCargo.self
			typeRegistry[.embark] = Journal.Embark.self
			typeRegistry[.endCrewSession] = Journal.EndCrewSession.self
			typeRegistry[.engineerApply] = Journal.EngineerApply.self
			typeRegistry[.engineerContribution] = Journal.EngineerContribution.self
			typeRegistry[.engineerCraft] = Journal.EngineerCraft.self
			typeRegistry[.engineerLegacyConvert] = Journal.EngineerLegacyConvert.self
			typeRegistry[.engineerProgress] = Journal.EngineerProgress.self
			typeRegistry[.escapeInterdiction] = Journal.EscapeInterdiction.self
			typeRegistry[.factionKillBond] = Journal.FactionKillBond.self
			typeRegistry[.fetchRemoteModule] = Journal.FetchRemoteModule.self
			typeRegistry[.fieldMaintenanceRepairs] = Journal.FieldMaintenanceRepairs.self
			typeRegistry[.fighterDestroyed] = Journal.FighterDestroyed.self
			typeRegistry[.fighterRebuilt] = Journal.FighterRebuilt.self
			typeRegistry[.fileHeader] = Journal.FileHeader.self
			typeRegistry[.fleetCarrierMaterials] = Journal.FleetCarrierMaterials.self
			typeRegistry[.friends] = Journal.Friends.self
			typeRegistry[.fuelScoop] = Journal.FuelScoop.self
			typeRegistry[.heatDamage] = Journal.HeatDamage.self
			typeRegistry[.heatWarning] = Journal.HeatWarning.self
			typeRegistry[.holoscreenHacked] = Journal.HoloscreenHacked.self
			typeRegistry[.hullDamage] = Journal.HullDamage.self
			typeRegistry[.interdicted] = Journal.Interdicted.self
			typeRegistry[.interdiction] = Journal.Interdiction.self
			typeRegistry[.invitedToSquadron] = Journal.Squadron.self
			typeRegistry[.jetConeBoost] = Journal.JetConeBoost.self
			typeRegistry[.jetConeDamage] = Journal.JetConeDamage.self
			typeRegistry[.joinCrew] = Journal.JoinCrew.self
			typeRegistry[.joinedSquadron] = Journal.Squadron.self
			typeRegistry[.jumpSystem] = Journal.JumpSystem.self
			typeRegistry[.kickCrewMember] = Journal.KickCrewMember.self
			typeRegistry[.kickedFromSquadron] = Journal.Squadron.self
			typeRegistry[.launchBuggy] = Journal.LaunchBuggy.self
			typeRegistry[.launchDrone] = Journal.LaunchDrone.self
			typeRegistry[.launchFighter] = Journal.LaunchFighter.self
			typeRegistry[.leaveBody] = Journal.LeaveBody.self
			typeRegistry[.leftSquadron] = Journal.Squadron.self
			typeRegistry[.liftoff] = Journal.Liftoff.self
			typeRegistry[.loadGame] = Journal.LoadGame.self
			typeRegistry[.loadout] = Journal.Loadout.self
			typeRegistry[.loadoutEquipModule] = Journal.LoadoutEquipModule.self
			typeRegistry[.loadoutRemoveModule] = Journal.LoadoutRemoveModule.self
			typeRegistry[.location] = Journal.Location.self
			typeRegistry[.market] = Journal.Market.self
			typeRegistry[.marketBuy] = Journal.MarketBuy.self
			typeRegistry[.marketSell] = Journal.MarketSell.self
			typeRegistry[.massModuleStore] = Journal.MassModuleStore.self
			typeRegistry[.materialCollected] = Journal.MaterialCollected.self
			typeRegistry[.materialDiscarded] = Journal.MaterialDiscarded.self
			typeRegistry[.materialDiscovered] = Journal.MaterialDiscovered.self
			typeRegistry[.materials] = Journal.Materials.self
			typeRegistry[.materialTrade] = Journal.MaterialTrade.self
			typeRegistry[.miningRefined] = Journal.MiningRefined.self
			typeRegistry[.missionAbandoned] = Journal.MissionAbandoned.self
			typeRegistry[.missionAccepted] = Journal.MissionAccepted.self
			typeRegistry[.missionCompleted] = Journal.MissionCompleted.self
			typeRegistry[.missionFailed] = Journal.MissionFailed.self
			typeRegistry[.missionRedirected] = Journal.MissionRedirected.self
			typeRegistry[.missions] = Journal.Missions.self
			typeRegistry[.moduleBuy] = Journal.ModuleBuy.self
			typeRegistry[.moduleBuyAndStore] = Journal.ModuleBuyAndStore.self
			typeRegistry[.moduleInfo] = Journal.ModuleInfo.self
			typeRegistry[.moduleRetrieve] = Journal.ModuleRetrieve.self
			typeRegistry[.moduleSell] = Journal.ModuleSell.self
			typeRegistry[.moduleSellRemote] = Journal.ModuleSellRemote.self
			typeRegistry[.moduleStore] = Journal.ModuleStore.self
			typeRegistry[.moduleSwap] = Journal.ModuleSwap.self
			typeRegistry[.multiSellExplorationData] = Journal.MultiSellExplorationData.self
			typeRegistry[.music] = Journal.Music.self
			typeRegistry[.navBeaconScan] = Journal.NavBeaconScan.self
			typeRegistry[.navRoute] = Journal.NavRoute.self
			typeRegistry[.navRouteClear] = Journal.NavRouteClear.self
			typeRegistry[.newCommander] = Journal.NewCommander.self
			typeRegistry[.npcCrewPaidWage] = Journal.NpcCrewPaidWage.self
			typeRegistry[.npcCrewRank] = Journal.NpcCrewRank.self
			typeRegistry[.outfitting] = Journal.Outfitting.self
			typeRegistry[.passengers] = Journal.Passengers.self
			typeRegistry[.payBounties] = Journal.PayBounties.self
			typeRegistry[.payFines] = Journal.PayFines.self
			typeRegistry[.payLegacyFines] = Journal.PayLegacyFines.self
			typeRegistry[.playerKill] = Journal.PlayerKill.self
			typeRegistry[.powerplay] = Journal.Powerplay.self
			typeRegistry[.powerplayCollect] = Journal.PowerplayCollect.self
			typeRegistry[.powerplayDefect] = Journal.PowerplayDefect.self
			typeRegistry[.powerplayDeliver] = Journal.PowerplayDeliver.self
			typeRegistry[.powerplayFastTrack] = Journal.PowerplayFastTrack.self
			typeRegistry[.powerplayJoin] = Journal.PowerplayJoin.self
			typeRegistry[.powerplayLeave] = Journal.PowerplayLeave.self
			typeRegistry[.powerplaySalary] = Journal.PowerplaySalary.self
			typeRegistry[.powerplayVote] = Journal.PowerplayVote.self
			typeRegistry[.powerplayVoucher] = Journal.PowerplayVoucher.self
			typeRegistry[.progress] = Journal.Progress.self
			typeRegistry[.promotion] = Journal.Promotion.self
			typeRegistry[.prospectedAsteroid] = Journal.ProspectedAsteroid.self
			typeRegistry[.quitCrew] = Journal.QuitCrew.self
			typeRegistry[.rank] = Journal.Rank.self
			typeRegistry[.rebootRepair] = Journal.RebootRepair.self
			typeRegistry[.receiveText] = Journal.ReceiveText.self
			typeRegistry[.redeemVoucher] = Journal.RedeemVoucher.self
			typeRegistry[.refuelAll] = Journal.RefuelAll.self
			typeRegistry[.refuelPartial] = Journal.RefuelPartial.self
			typeRegistry[.renameSuitLoadout] = Journal.RenameSuitLoadout.self
			typeRegistry[.repair] = Journal.Repair.self
			typeRegistry[.repairAll] = Journal.RepairAll.self
			typeRegistry[.repairDrone] = Journal.RepairDrone.self
			typeRegistry[.reputation] = Journal.Reputation.self
			typeRegistry[.requestPowerMicroResources] = Journal.RequestPowerMicroResources.self
			typeRegistry[.reservoirReplenished] = Journal.ReservoirReplenished.self
			typeRegistry[.restockVehicle] = Journal.RestockVehicle.self
			typeRegistry[.resupply] = Journal.Resupply.self
			typeRegistry[.resurrect] = Journal.Resurrect.self
			typeRegistry[.scan] = Journal.Scan.self
			typeRegistry[.scanBarycenter] = Journal.ScanBarycenter.self
			typeRegistry[.scanned] = Journal.Scanned.self
			typeRegistry[.scanOrganic] = Journal.ScanOrganic.self
			typeRegistry[.scientificResearch] = Journal.ScientificResearch.self
			typeRegistry[.screenshot] = Journal.Screenshot.self
			typeRegistry[.searchAndRescue] = Journal.SearchAndRescue.self
			typeRegistry[.selfDestruct] = Journal.SelfDestruct.self
			typeRegistry[.sellDrones] = Journal.SellDrones.self
			typeRegistry[.sellExplorationData] = Journal.SellExplorationData.self
			typeRegistry[.sellMicroResources] = Journal.SellMicroResources.self
			typeRegistry[.sellOrganicData] = Journal.SellOrganicData.self
			typeRegistry[.sellShipOnRebuy] = Journal.SellShipOnRebuy.self
			typeRegistry[.sellSuit] = Journal.SellSuit.self
			typeRegistry[.sellWeapon] = Journal.SellWeapon.self
			typeRegistry[.sendText] = Journal.SendText.self
			typeRegistry[.setUserShipName] = Journal.SetUserShipName.self
			typeRegistry[.sharedBookmarkToSquadron] = Journal.Squadron.self
			typeRegistry[.shieldState] = Journal.ShieldState.self
			typeRegistry[.shipLocker] = Journal.ShipLocker.self
			typeRegistry[.shipLockerMaterials] = Journal.ShipLockerMaterials.self
			typeRegistry[.shipRedeemed] = Journal.ShipRedeemed.self
			typeRegistry[.shipTargeted] = Journal.ShipTargeted.self
			typeRegistry[.shipyard] = Journal.Shipyard.self
			typeRegistry[.shipyardBuy] = Journal.ShipyardBuy.self
			typeRegistry[.shipyardNew] = Journal.ShipyardNew.self
			typeRegistry[.shipyardRedeem] = Journal.ShipyardRedeem.self
			typeRegistry[.shipyardSell] = Journal.ShipyardSell.self
			typeRegistry[.shipyardSwap] = Journal.ShipyardSwap.self
			typeRegistry[.shipyardTransfer] = Journal.ShipyardTransfer.self
			typeRegistry[.shutdown] = Journal.Shutdown.self
			typeRegistry[.signalDiscovered] = Journal.SignalDiscovered.self
			typeRegistry[.signalDrop] = Journal.SignalDrop.self
			typeRegistry[.squadronCreated] = Journal.Squadron.self
			typeRegistry[.squadronDemotion] = Journal.SquadronRankChange.self
			typeRegistry[.squadronPromotion] = Journal.SquadronRankChange.self
			typeRegistry[.squadronStartup] = Journal.SquadronStartup.self
			typeRegistry[.startJump] = Journal.StartJump.self
			typeRegistry[.statistics] = Journal.Statistics.self
			typeRegistry[.status] = Journal.Status.self
			typeRegistry[.storedModules] = Journal.StoredModules.self
			typeRegistry[.storedShips] = Journal.StoredShips.self
			typeRegistry[.suitLoadout] = Journal.SuitLoadout.self
			typeRegistry[.supercruiseDestinationDrop] = Journal.SupercruiseDestinationDrop.self
			typeRegistry[.supercruiseEntry] = Journal.SupercruiseEntry.self
			typeRegistry[.supercruiseExit] = Journal.SupercruiseExit.self
			typeRegistry[.surfaceScanComplete] = Journal.SurfaceScanComplete.self
			typeRegistry[.surfaceSignalsFound] = Journal.SurfaceSignalsFound.self
			typeRegistry[.switchSuitLoadout] = Journal.SwitchSuitLoadout.self
			typeRegistry[.synthesis] = Journal.Synthesis.self
			typeRegistry[.systemsShutdown] = Journal.SystemsShutdown.self
			typeRegistry[.targetSystem] = Journal.TargetSystem.self
			typeRegistry[.technologyBroker] = Journal.TechnologyBroker.self
			typeRegistry[.touchdown] = Journal.Touchdown.self
			typeRegistry[.tradeMicroResources] = Journal.TradeMicroResources.self
			typeRegistry[.transferMicroResources] = Journal.TransferMicroResources.self
			typeRegistry[.underAttack] = Journal.UnderAttack.self
			typeRegistry[.undocked] = Journal.Undocked.self
			typeRegistry[.upgradeSuit] = Journal.UpgradeSuit.self
			typeRegistry[.upgradeWeapon] = Journal.UpgradeWeapon.self
			typeRegistry[.useConsumable] = Journal.UseConsumable.self
			typeRegistry[.vehicleSwitch] = Journal.VehicleSwitch.self
			typeRegistry[.wingAdd] = Journal.WingAdd.self
			typeRegistry[.wingInvite] = Journal.WingInvite.self
			typeRegistry[.wingJoin] = Journal.WingJoin.self
			typeRegistry[.wingLeave] = Journal.WingLeave.self
			typeRegistry[.wonTrophy] = Journal.Squadron.self

			self.typeRegistry = typeRegistry
		}

		public func load(json: PrismaticJsonObject) -> Journal {
			guard let eventName: String = json["event"],
				let event = Journal.Event(rawValue: eventName.lowercased())
			else {
				return Journal(json: json, event: .invalidEvent)
			}

			guard let type: Journal.Type = typeRegistry[event] else {
				return Journal(json: json, event: event)
			}

			return type.init(json: json, event: event)
		}
	}
}
