// SPDX-FileCopyrightText: 2025 Legiayayana <ada@chronovore.dev>
// SPDX-License-Identifier: EUPL-1.2

/// Journal Event Registration and dispatch system.
public struct JournalEventRegistry: Sendable {
	fileprivate typealias Registry = [JournalEvent: JournalEntry.Type]
	private let typeRegistry: Registry

	public static let `default`: JournalEventRegistry = JournalEventRegistry()

	init() {
		var typeRegistry: Registry = [:]

		typeRegistry[.allBodiesFound] = JournalAllBodiesFound.self
		typeRegistry[.appliedToSquadron] = JournalSquadron.self
		typeRegistry[.approachBody] = JournalApproachBody.self
		typeRegistry[.approachSettlement] = JournalApproachSettlement.self
		typeRegistry[.asteroidCracked] = JournalAsteroidCracked.self
		typeRegistry[.autoDiscoveryScan] = JournalAutoDiscoveryScan.self
		typeRegistry[.backpack] = JournalBackpack.self
		typeRegistry[.backpackChange] = JournalBackpackChange.self
		typeRegistry[.backpackMaterials] = JournalBackpackMaterials.self
		typeRegistry[.bodySignals] = JournalBodySignals.self
		typeRegistry[.bookDropship] = JournalBookDropship.self
		typeRegistry[.bookTaxi] = JournalBookTaxi.self
		typeRegistry[.bounty] = JournalBounty.self
		typeRegistry[.buggyDestroyed] = JournalBuggyDestroyed.self
		typeRegistry[.buyAmmo] = JournalBuyAmmo.self
		typeRegistry[.buyDrones] = JournalBuyDrones.self
		typeRegistry[.buyExplorationData] = JournalBuyExplorationData.self
		typeRegistry[.buyMicroResources] = JournalBuyMicroResources.self
		typeRegistry[.buySuit] = JournalBuySuit.self
		typeRegistry[.buyTradeData] = JournalBuyTradeData.self
		typeRegistry[.buyWeapon] = JournalBuyWeapon.self
		typeRegistry[.cancelDropship] = JournalCancelDropship.self
		typeRegistry[.cancelTaxi] = JournalCancelTaxi.self
		typeRegistry[.capitalShipBond] = JournalCapitalShipBond.self
		typeRegistry[.cargo] = JournalCargo.self
		typeRegistry[.cargoDepot] = JournalCargoDepot.self
		typeRegistry[.cargoTransfer] = JournalCargoTransfer.self
		typeRegistry[.carrierBankTransfer] = JournalCarrierBankTransfer.self
		typeRegistry[.carrierBuy] = JournalCarrierBuy.self
		typeRegistry[.carrierCancelDecommission] = JournalCarrierCancelDecommission.self
		typeRegistry[.carrierCrewServices] = JournalCarrierCrewServices.self
		typeRegistry[.carrierDecommission] = JournalCarrierDecommission.self
		typeRegistry[.carrierDepositFuel] = JournalCarrierDepositFuel.self
		typeRegistry[.carrierDockingPermission] = JournalCarrierDockingPermission.self
		typeRegistry[.carrierFinance] = JournalCarrierFinance.self
		typeRegistry[.carrierJump] = JournalCarrierJump.self
		typeRegistry[.carrierJumpCancelled] = JournalCarrierJumpCancelled.self
		typeRegistry[.carrierJumpRequest] = JournalCarrierJumpRequest.self
		typeRegistry[.carrierModulePack] = JournalCarrierModulePack.self
		typeRegistry[.carrierNameChange] = JournalCarrierNameChange.self
		typeRegistry[.carrierShipPack] = JournalCarrierShipPack.self
		typeRegistry[.carrierStats] = JournalCarrierStats.self
		typeRegistry[.carrierTradeOrder] = JournalCarrierTradeOrder.self
		typeRegistry[.changeCrewRole] = JournalChangeCrewRole.self
		typeRegistry[.clearImpound] = JournalClearImpound.self
		typeRegistry[.clearSavedGame] = JournalCommander.self
		typeRegistry[.cockpitBreached] = JournalCockpitBreached.self
		typeRegistry[.codexEntry] = JournalCodexEntry.self
		typeRegistry[.collectCargo] = JournalCollectCargo.self
		typeRegistry[.collectItems] = JournalCollectItems.self
		typeRegistry[.commander] = JournalCommander.self
		typeRegistry[.commitCrime] = JournalCommitCrime.self
		typeRegistry[.communityGoal] = JournalCommunityGoal.self
		typeRegistry[.communityGoalDiscard] = JournalCommunityGoalDiscard.self
		typeRegistry[.communityGoalJoin] = JournalCommunityGoalJoin.self
		typeRegistry[.communityGoalReward] = JournalCommunityGoalReward.self
		typeRegistry[.continued] = JournalContinued.self
		typeRegistry[.createSuitLoadout] = JournalCreateSuitLoadout.self
		typeRegistry[.crewAssign] = JournalCrewAssign.self
		typeRegistry[.crewFire] = JournalCrewFire.self
		typeRegistry[.crewHire] = JournalCrewHire.self
		typeRegistry[.crewLaunchFighter] = JournalCrewLaunchFighter.self
		typeRegistry[.crewMemberJoins] = JournalCrewMemberJoins.self
		typeRegistry[.crewMemberQuits] = JournalCrewMemberQuits.self
		typeRegistry[.crewMemberRoleChange] = JournalCrewMemberRoleChange.self
		typeRegistry[.crimeVictim] = JournalCrimeVictim.self
		typeRegistry[.datalinkScan] = JournalDatalinkScan.self
		typeRegistry[.datalinkVoucher] = JournalDatalinkVoucher.self
		typeRegistry[.dataScanned] = JournalDataScanned.self
		typeRegistry[.deleteSuitLoadout] = JournalDeleteSuitLoadout.self
		typeRegistry[.deliverPowerMicroResources] = JournalDeliverPowerMicroResources.self
		typeRegistry[.died] = JournalDied.self
		typeRegistry[.disbandedSquadron] = JournalSquadron.self
		typeRegistry[.discoveryScan] = JournalDiscoveryScan.self
		typeRegistry[.disembark] = JournalDisembark.self
		typeRegistry[.dockBuggy] = JournalDockBuggy.self
		typeRegistry[.docked] = JournalDocked.self
		typeRegistry[.dockFighter] = JournalDockFighter.self
		typeRegistry[.dockingCancelled] = JournalDockingCancelled.self
		typeRegistry[.dockingDenied] = JournalDockingDenied.self
		typeRegistry[.dockingGranted] = JournalDockingGranted.self
		typeRegistry[.dockingRequested] = JournalDockingRequested.self
		typeRegistry[.dockingTimeout] = JournalDockingTimeout.self
		typeRegistry[.dropItems] = JournalDropItems.self
		typeRegistry[.dropshipDeploy] = JournalDropshipDeploy.self
		typeRegistry[.ejectCargo] = JournalEjectCargo.self
		typeRegistry[.embark] = JournalEmbark.self
		typeRegistry[.endCrewSession] = JournalEndCrewSession.self
		typeRegistry[.engineerApply] = JournalEngineerApply.self
		typeRegistry[.engineerContribution] = JournalEngineerContribution.self
		typeRegistry[.engineerCraft] = JournalEngineerCraft.self
		typeRegistry[.engineerLegacyConvert] = JournalEngineerLegacyConvert.self
		typeRegistry[.engineerProgress] = JournalEngineerProgress.self
		typeRegistry[.escapeInterdiction] = JournalEscapeInterdiction.self
		typeRegistry[.factionKillBond] = JournalFactionKillBond.self
		typeRegistry[.fetchRemoteModule] = JournalFetchRemoteModule.self
		typeRegistry[.fieldMaintenanceRepairs] = JournalFieldMaintenanceRepairs.self
		typeRegistry[.fighterDestroyed] = JournalFighterDestroyed.self
		typeRegistry[.fighterRebuilt] = JournalFighterRebuilt.self
		typeRegistry[.fileHeader] = JournalFileHeader.self
		typeRegistry[.fleetCarrierMaterials] = JournalFleetCarrierMaterials.self
		typeRegistry[.friends] = JournalFriends.self
		typeRegistry[.fuelScoop] = JournalFuelScoop.self
		typeRegistry[.heatDamage] = JournalHeatDamage.self
		typeRegistry[.heatWarning] = JournalHeatWarning.self
		typeRegistry[.holoscreenHacked] = JournalHoloscreenHacked.self
		typeRegistry[.hullDamage] = JournalHullDamage.self
		typeRegistry[.interdicted] = JournalInterdicted.self
		typeRegistry[.interdiction] = JournalInterdiction.self
		typeRegistry[.invitedToSquadron] = JournalSquadron.self
		typeRegistry[.jetConeBoost] = JournalJetConeBoost.self
		typeRegistry[.jetConeDamage] = JournalJetConeDamage.self
		typeRegistry[.joinCrew] = JournalJoinCrew.self
		typeRegistry[.joinedSquadron] = JournalSquadron.self
		typeRegistry[.jumpSystem] = JournalJumpSystem.self
		typeRegistry[.kickCrewMember] = JournalKickCrewMember.self
		typeRegistry[.kickedFromSquadron] = JournalSquadron.self
		typeRegistry[.launchBuggy] = JournalLaunchBuggy.self
		typeRegistry[.launchDrone] = JournalLaunchDrone.self
		typeRegistry[.launchFighter] = JournalLaunchFighter.self
		typeRegistry[.leaveBody] = JournalLeaveBody.self
		typeRegistry[.leftSquadron] = JournalSquadron.self
		typeRegistry[.liftoff] = JournalLiftoff.self
		typeRegistry[.loadGame] = JournalLoadGame.self
		typeRegistry[.loadout] = JournalLoadout.self
		typeRegistry[.loadoutEquipModule] = JournalLoadoutEquipModule.self
		typeRegistry[.loadoutRemoveModule] = JournalLoadoutRemoveModule.self
		typeRegistry[.location] = JournalLocation.self
		typeRegistry[.market] = JournalMarket.self
		typeRegistry[.marketBuy] = JournalMarketBuy.self
		typeRegistry[.marketSell] = JournalMarketSell.self
		typeRegistry[.massModuleStore] = JournalMassModuleStore.self
		typeRegistry[.materialCollected] = JournalMaterialCollected.self
		typeRegistry[.materialDiscarded] = JournalMaterialDiscarded.self
		typeRegistry[.materialDiscovered] = JournalMaterialDiscovered.self
		typeRegistry[.materials] = JournalMaterials.self
		typeRegistry[.materialTrade] = JournalMaterialTrade.self
		typeRegistry[.miningRefined] = JournalMiningRefined.self
		typeRegistry[.missionAbandoned] = JournalMissionAbandoned.self
		typeRegistry[.missionAccepted] = JournalMissionAccepted.self
		typeRegistry[.missionCompleted] = JournalMissionCompleted.self
		typeRegistry[.missionFailed] = JournalMissionFailed.self
		typeRegistry[.missionRedirected] = JournalMissionRedirected.self
		typeRegistry[.missions] = JournalMissions.self
		typeRegistry[.moduleBuy] = JournalModuleBuy.self
		typeRegistry[.moduleBuyAndStore] = JournalModuleBuyAndStore.self
		typeRegistry[.moduleInfo] = JournalModuleInfo.self
		typeRegistry[.moduleRetrieve] = JournalModuleRetrieve.self
		typeRegistry[.moduleSell] = JournalModuleSell.self
		typeRegistry[.moduleSellRemote] = JournalModuleSellRemote.self
		typeRegistry[.moduleStore] = JournalModuleStore.self
		typeRegistry[.moduleSwap] = JournalModuleSwap.self
		typeRegistry[.multiSellExplorationData] = JournalMultiSellExplorationData.self
		typeRegistry[.music] = JournalMusic.self
		typeRegistry[.navBeaconScan] = JournalNavBeaconScan.self
		typeRegistry[.navRoute] = JournalNavRoute.self
		typeRegistry[.navRouteClear] = JournalNavRouteClear.self
		typeRegistry[.newCommander] = JournalNewCommander.self
		typeRegistry[.npcCrewPaidWage] = JournalNpcCrewPaidWage.self
		typeRegistry[.npcCrewRank] = JournalNpcCrewRank.self
		typeRegistry[.outfitting] = JournalOutfitting.self
		typeRegistry[.passengers] = JournalPassengers.self
		typeRegistry[.payBounties] = JournalPayBounties.self
		typeRegistry[.payFines] = JournalPayFines.self
		typeRegistry[.payLegacyFines] = JournalPayLegacyFines.self
		typeRegistry[.playerKill] = JournalPlayerKill.self
		typeRegistry[.powerplay] = JournalPowerplay.self
		typeRegistry[.powerplayCollect] = JournalPowerplayCollect.self
		typeRegistry[.powerplayDefect] = JournalPowerplayDefect.self
		typeRegistry[.powerplayDeliver] = JournalPowerplayDeliver.self
		typeRegistry[.powerplayFastTrack] = JournalPowerplayFastTrack.self
		typeRegistry[.powerplayJoin] = JournalPowerplayJoin.self
		typeRegistry[.powerplayLeave] = JournalPowerplayLeave.self
		typeRegistry[.powerplaySalary] = JournalPowerplaySalary.self
		typeRegistry[.powerplayVote] = JournalPowerplayVote.self
		typeRegistry[.powerplayVoucher] = JournalPowerplayVoucher.self
		typeRegistry[.progress] = JournalProgress.self
		typeRegistry[.promotion] = JournalPromotion.self
		typeRegistry[.prospectedAsteroid] = JournalProspectedAsteroid.self
		typeRegistry[.quitCrew] = JournalQuitCrew.self
		typeRegistry[.rank] = JournalRank.self
		typeRegistry[.rebootRepair] = JournalRebootRepair.self
		typeRegistry[.receiveText] = JournalReceiveText.self
		typeRegistry[.redeemVoucher] = JournalRedeemVoucher.self
		typeRegistry[.refuelAll] = JournalRefuelAll.self
		typeRegistry[.refuelPartial] = JournalRefuelPartial.self
		typeRegistry[.renameSuitLoadout] = JournalRenameSuitLoadout.self
		typeRegistry[.repair] = JournalRepair.self
		typeRegistry[.repairAll] = JournalRepairAll.self
		typeRegistry[.repairDrone] = JournalRepairDrone.self
		typeRegistry[.reputation] = JournalReputation.self
		typeRegistry[.requestPowerMicroResources] = JournalRequestPowerMicroResources.self
		typeRegistry[.reservoirReplenished] = JournalReservoirReplenished.self
		typeRegistry[.restockVehicle] = JournalRestockVehicle.self
		typeRegistry[.resupply] = JournalResupply.self
		typeRegistry[.resurrect] = JournalResurrect.self
		typeRegistry[.scan] = JournalScan.self
		typeRegistry[.scanBarycenter] = JournalScanBarycenter.self
		typeRegistry[.scanned] = JournalScanned.self
		typeRegistry[.scanOrganic] = JournalScanOrganic.self
		typeRegistry[.scientificResearch] = JournalScientificResearch.self
		typeRegistry[.screenshot] = JournalScreenshot.self
		typeRegistry[.searchAndRescue] = JournalSearchAndRescue.self
		typeRegistry[.selfDestruct] = JournalSelfDestruct.self
		typeRegistry[.sellDrones] = JournalSellDrones.self
		typeRegistry[.sellExplorationData] = JournalSellExplorationData.self
		typeRegistry[.sellMicroResources] = JournalSellMicroResources.self
		typeRegistry[.sellOrganicData] = JournalSellOrganicData.self
		typeRegistry[.sellShipOnRebuy] = JournalSellShipOnRebuy.self
		typeRegistry[.sellSuit] = JournalSellSuit.self
		typeRegistry[.sellWeapon] = JournalSellWeapon.self
		typeRegistry[.sendText] = JournalSendText.self
		typeRegistry[.setUserShipName] = JournalSetUserShipName.self
		typeRegistry[.sharedBookmarkToSquadron] = JournalSquadron.self
		typeRegistry[.shieldState] = JournalShieldState.self
		typeRegistry[.shipLocker] = JournalShipLocker.self
		typeRegistry[.shipLockerMaterials] = JournalShipLockerMaterials.self
		typeRegistry[.shipRedeemed] = JournalShipRedeemed.self
		typeRegistry[.shipTargeted] = JournalShipTargeted.self
		typeRegistry[.shipyard] = JournalShipyard.self
		typeRegistry[.shipyardBuy] = JournalShipyardBuy.self
		typeRegistry[.shipyardNew] = JournalShipyardNew.self
		typeRegistry[.shipyardRedeem] = JournalShipyardRedeem.self
		typeRegistry[.shipyardSell] = JournalShipyardSell.self
		typeRegistry[.shipyardSwap] = JournalShipyardSwap.self
		typeRegistry[.shipyardTransfer] = JournalShipyardTransfer.self
		typeRegistry[.shutdown] = JournalShutdown.self
		typeRegistry[.signalDiscovered] = JournalSignalDiscovered.self
		typeRegistry[.signalDrop] = JournalSignalDrop.self
		typeRegistry[.squadronCreated] = JournalSquadron.self
		typeRegistry[.squadronDemotion] = JournalSquadronRankChange.self
		typeRegistry[.squadronPromotion] = JournalSquadronRankChange.self
		typeRegistry[.squadronStartup] = JournalSquadronStartup.self
		typeRegistry[.startJump] = JournalStartJump.self
		typeRegistry[.statistics] = JournalStatistics.self
		typeRegistry[.status] = JournalStatus.self
		typeRegistry[.storedModules] = JournalStoredModules.self
		typeRegistry[.storedShips] = JournalStoredShips.self
		typeRegistry[.suitLoadout] = JournalSuitLoadout.self
		typeRegistry[.supercruiseDestinationDrop] = JournalSupercruiseDestinationDrop.self
		typeRegistry[.supercruiseEntry] = JournalSupercruiseEntry.self
		typeRegistry[.supercruiseExit] = JournalSupercruiseExit.self
		typeRegistry[.surfaceScanComplete] = JournalSurfaceScanComplete.self
		typeRegistry[.surfaceSignalsFound] = JournalSurfaceSignalsFound.self
		typeRegistry[.switchSuitLoadout] = JournalSwitchSuitLoadout.self
		typeRegistry[.synthesis] = JournalSynthesis.self
		typeRegistry[.systemsShutdown] = JournalSystemsShutdown.self
		typeRegistry[.targetSystem] = JournalTargetSystem.self
		typeRegistry[.technologyBroker] = JournalTechnologyBroker.self
		typeRegistry[.touchdown] = JournalTouchdown.self
		typeRegistry[.tradeMicroResources] = JournalTradeMicroResources.self
		typeRegistry[.transferMicroResources] = JournalTransferMicroResources.self
		typeRegistry[.underAttack] = JournalUnderAttack.self
		typeRegistry[.undocked] = JournalUndocked.self
		typeRegistry[.upgradeSuit] = JournalUpgradeSuit.self
		typeRegistry[.upgradeWeapon] = JournalUpgradeWeapon.self
		typeRegistry[.useConsumable] = JournalUseConsumable.self
		typeRegistry[.vehicleSwitch] = JournalVehicleSwitch.self
		typeRegistry[.wingAdd] = JournalWingAdd.self
		typeRegistry[.wingInvite] = JournalWingInvite.self
		typeRegistry[.wingJoin] = JournalWingJoin.self
		typeRegistry[.wingLeave] = JournalWingLeave.self
		typeRegistry[.wonTrophy] = JournalSquadron.self

		self.typeRegistry = typeRegistry
	}

	public func load(json: PrismaticJsonObject) -> JournalEntry {
		guard let eventName: String = json["event"],
			let event = JournalEvent(rawValue: eventName.lowercased())
		else {
			return JournalEntry(json: json, event: .invalidEvent)
		}

		guard let type: JournalEntry.Type = typeRegistry[event] else {
			return JournalEntry(json: json, event: event)
		}

		return type.init(json: json, event: event)
	}
}
